config/routes.rb
Rails.application.routes.draw do
  resources :pages
  mount Thredded::Engine => '/forum'
  resources :support_requests
  resources :board_members_terms
  resources :association_details
  resources :event_applicants
  resources :events do
    member do
      get 'apply'
    end
  end
  resources :payments do
    collection do
      get 'member_fees'
    end
    member do
      get 'confirm'
    end
  end
  resources :mp_amount_settings
  resources :mp_years
  resources :membership_types
  resources :budget_years
  resources :training_materials
  resources :training_methods
  resources :training_funds do
    collection do
      get 'funding_by_area'
    end
  end
  resources :trainee_distributions
  resources :educations
  resources :work_experiences
  resources :trainer_profiles
  resources :languages
  resources :professions
  resources :profession_categories
  get 'reports/trainings'
  post 'reports/trainings'
  get 'reports/health_workers'
  post 'reports/health_workers'
  get 'reports/trainees'
  post 'reports/trainees'
  get 'reports/members'
  post 'reports/members'

  resources :trainees do
    collection do
      get 'load_trainees'
      get 'institution_trainees_by_area'
      get 'institution_trainees_by_region'
      get 'institution_trainees_by_year'

      get 'org_unit_trainees_by_area'
      get 'org_unit_trainees_by_year'
      get 'org_unit_trainees_by_category'
    end
  end
  resources :trainers
  resources :people do
    member do
      get 'membership_idcard'
      get 'confirm'
    end
    collection do
      get 'load_people'
      get 'load_professions'
      get 'members_by_type'
      get 'members_by_membership_type_and_payment_status'
      get 'members_paid'
      get 'load_members_paid'
      get 'members_not_paid'
      get 'load_members_not_paid'
    end
  end
  resources :facilities do
    collection do
      get 'load_facilities'
    end
  end
  resources :facility_types
  resources :trainings do
    collection do
      get 'load_distribution'
    end
    member do
      delete 'cancel'
      get 'undo_cancel'
    end
  end

  resources :training_titles do
    collection do
      get 'training_titles_by_area'
      get 'load_training_titles'
    end
  end

  resources :program_areas
  resources :institutions
  resources :institution_types
  resources :organization_units do
    collection do
      get 'load_tree'
      get 'load_sub_units'
      get 'org_unit_facilities'
    end
  end
  resources :organization_types
  resources :roles
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  scope "/admin" do
    resources :users do
      member do
        get 'confirm'
      end
      collection do
        get 'load_users'
        get 'institution_users'
        get 'new_institution_user'
        get 'edit_institution_user'
      end
    end
  end
  get 'home/index'
  get 'home/landing_page'
  get 'payment_dashboard', to: 'home#payment_dashboard'
  get 'training_dashboard', to: 'home#training_dashboard'
  get 'member_dashboard', to: 'home#member_dashboard'

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  root to: "home#landing_page"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :training_title
  belongs_to :institution, optional: true
  belongs_to :budget_year
  has_many :training_funds, dependent: :destroy
  has_many :trainers, dependent: :destroy
  has_many :trainees, dependent: :destroy
  has_many :trainee_distributions, dependent: :destroy
  accepts_nested_attributes_for :training_funds, allow_destroy: true

  TRAINING_STATUSES = [NOT_STARTED='Not Started', CANCELED='Canceled', IN_PROGRESS='In Progress', COMPLETED='Completed']

  validates :training_title_id, :training_type, :start_time, :end_time, :location, presence: true

  scope :upcoming_trainings, -> { where('date(start_time) >= ?',Date.today) }

  scope :trainings_in_progress, -> { where('date(start_time) <= ? and date(end_time) >= ?',Date.today,Date.today) }

  scope :type_trainings, -> (type) { where('training_type = ?', type)}

  scope :all_institution_trainings, -> (ins,from=nil,to=nil){ ins.trainings.where('start_time >= ? and start_time <= ?',from || true, to || Date::Infinity) +
      Training.joins(:training_funds).where('start_time >= ? and start_time <= ? and training_funds.institution_id = ?',from || true, to || Date::Infinity,ins.id) }

  scope :all_org_trainings, -> (org,from=nil,to=nil) { (Training.where('start_time >= ? and start_time <= ? and organization_unit_id in (?)', from || true, to || Date::Infinity, org.sub_units.pluck(:id) << org.id) +
      Training.joins(:trainee_distributions).where('start_time >= ? and start_time <= ? and trainee_distributions.organization_unit_id in (?)', from || true, to || Date::Infinity, org.sub_units.pluck(:id) << org.id)).uniq}

  def training_status
    if status.blank?
      start_time > Date.today ? Training::NOT_STARTED : (start_time <= Date.today and end_time >= Date.today ? Training::IN_PROGRESS : Training::COMPLETED)
    else
      status
    end
  end

  def max_possible_trainees(org_unit)
    if org_unit == OrganizationUnit.top_organization_unit
      return training_title.maximum_number_of_participants
    elsif !org_unit.blank?
      return trainee_distributions.where('organization_unit_id = ?', org_unit.id).pluck(:number_of_trainees).sum
    else
      return 0
    end
  end

  def total_trainees(org_unit)
    if org_unit == OrganizationUnit.top_organization_unit
      return trainees.count
    else
      return trainees.joins(:person).where('organization_unit_id in (?)', org_unit.sub_units.pluck(:id)).size
    end
  end

  def remaining_trainees(org_unit)
    return max_possible_trainees(org_unit) - total_trainees(org_unit)
  end

  def self.load_trainings(user,type=nil,from=nil,to=nil)
    trainings = []
    if type = 'all_upcoming'
      trainings = Training.upcoming_trainings
    elsif user.institution
      if type == 'Pre-Service'
        trainings = Training.type_trainings('Pre-Service').all_institution_trainings(user.institution,from,to)
      elsif type == 'In-Service'
        trainings = Training.type_trainings('In-Service').all_institution_trainings(user.institution)
      elsif type == 'upcoming'
        trainings = Training.upcoming_trainings.all_institution_trainings(user.institution,from,to)
      elsif type == 'progress'
        trainings = Training.trainings_in_progress.all_institution_trainings(user.institution,from,to)
      else
        trainings = Training.all_institution_trainings(user.institution,from,to)
      end
    elsif user.organization_unit
      if type == 'Pre-Service'
        trainings = Training.type_trainings('Pre-Service').all_org_trainings(user.organization_unit,from,to)
      elsif type == 'In-Service'
        trainings = Training.type_trainings('In-Service').all_org_trainings(user.organization_unit)
      elsif type == 'upcoming'
        trainings = Training.upcoming_trainings.all_org_trainings(user.organization_unit,from,to)
      elsif type == 'progress'
        trainings = Training.trainings_in_progress.all_org_trainings(user.organization_unit,from,to)
      else
        trainings = Training.all_org_trainings(user.organization_unit,from,to)
      end
    end
    return trainings.uniq
  end

  def self.search_by_tpt(type, area, title)
    trainings = []
    if !type.blank? and !area.blank? and !title.blank?
      trainings = joins(:training_title).
          where('training_type = ? and program_area_id = ? and training_title_id = ?',type,area,title).uniq
    elsif !type.blank? and !area.blank?
      trainings = joins(:training_title).
          where('training_type = ? and program_area_id = ?',type,area).uniq
    elsif !type.blank? and !title.blank?
      trainings = where('training_type = ? and training_title_id = ?', type,title).uniq
    elsif !area.blank? and !title.blank?
      trainings = joins(:training_title).
          where('program_area_id = ? and training_title_id = ?',area,title).uniq
    elsif !type.blank?
      trainings = where('training_type = ?',type).uniq
    elsif !area.blank?
      trainings = joins(:training_title).where('program_area_id = ?',area).uniq
    elsif !title.blank?
      trainings = where('training_title_id = ?',title).uniq
    end
    return trainings
  end

  def name_and_date
    [to_s, '(',[start_time, end_time].join(' - '),')'].join(' ')
  end

  def to_s
    training_title
  end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy, :cancel, :undo_cancel]

  # GET /trainings
  # GET /trainings.json
  def index
    type = params[:type]
    @trainings = Training.load_trainings(current_user,type).uniq
  end
  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @organization_unit = current_user.organization_unit || OrganizationUnit.top_organization_unit
    @trainers = Person.all
    @trainee_distributions = []
    @organization_unit.sub_organization_units.each do |sub_unit|
      @trainee_distributions << TraineeDistribution.new(training_id: @training.id, organization_unit_id: sub_unit.id, number_of_trainees: sub_unit.trainee_distribution(@training.id).try(:number_of_trainees))
    end
  end

  def load_distribution
    @training = Training.find(params[:training])
    @organization_unit  = OrganizationUnit.find(params[:node])
    @trainee_distributions = []
    @organization_unit.sub_organization_units.each do |sub_unit|
      @trainee_distributions << TraineeDistribution.new(training_id: @training.id, organization_unit_id: sub_unit.id, number_of_trainees: sub_unit.trainee_distribution(@training.id).try(:number_of_trainees))
    end
    render partial: 'trainee_distributions'
  end


  # GET /trainings/new
  def new
    @training = Training.new
    @training.training_title_id = params[:training_title]
    @institutions = !@institution.blank? ? [@institution] : Institution.all
  end

  # GET /trainings/1/edit
  def edit
    @institutions = !@institution.blank? ? [@institution] : Institution.all
  end

  def cancel
    @training.update(status: Training::CANCELED)
    redirect_to @training, notice: "Training Successfully Canceled"
  end

  def undo_cancel
    @training.update(status: nil)
    redirect_to @training, notice: "Training Successfully Re-enabled"
  end
  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:category,:description,:training_title_id, :training_type, :start_time, :end_time,
                                       :organization_unit_id,:institution_id, :location, :budget_year_id)
    end
end

app/views/trainings/_form.html.erb
<%= simple_nested_form_for(@training) do |f| %>
  <%= f.error_notification %>
  <%= f.input :budget_year_id, as: :hidden, input_html: { value: BudgetYear.active.try(:id)} %>
  <%= f.input :organization_unit_id, as: :hidden, input_html: { value: current_user.organization_unit.try(:id)} %>
  <%= f.input :training_title_id, collection: TrainingTitle.all, class: "form-control show-tick" %>
  <%= f.input :training_type, label: 'Category', collection: ['In-Service', 'Pre-Service'], class: "form-control show-tick" %>
  <%= f.input :category, label: 'Type', collection: ['Basic', 'Refreshment', 'TOT'], class: "form-control show-tick" %>
  <%= f.association :institution, label: 'Organized by', collection: @institutions %>
  <%= f.input :start_time, as: :string,  input_html: {"data-format": "YYYY-MM-DD",class: "js-dtp"} %>
  <%= f.input :end_time, as: :string,  input_html: {"data-format": "YYYY-MM-DD",class: "js-dtp"} %>
  <%= f.input :location, class: "form-control show-tick" %>
  <%= f.input :description, class: "form-control show-tick" %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/trainings/_trainee_distributions.html.erb
<% unless @trainee_distributions.blank? %>
  <%= form_tag trainee_distributions_path do %>
    <%= hidden_field_tag 'training', @training.id %>
    <table class="table table-striped js-exportable">
      <thead>
      <tr>
        <th>Organization Unit</th>
        <th>Number of Trainees</th>
      </tr>
      </thead>

      <tbody>
      <% @trainee_distributions.each do |distribution| %>
        <%= fields_for 'distributions[]', distribution do |f| %>
          <%= f.hidden_field 'training_id' %>
          <%= f.hidden_field 'organization_unit_id' %>
          <tr>
            <td><%= distribution.organization_unit %></td>
            <td><%= f.number_field 'number_of_trainees' %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
    <div class="actions">
      <%= submit_tag "Save", class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

app/views/trainings/_training_fund_fields.html.erb
    <div class="card">
        <div class="header">
            <h2>
                Funders
            </h2>
        </div>
        <div class="body table-responsive">
        <%= f.simple_fields_for :training_funds, :wrapper => false do |tf| %>
            <div class='fields row'>
                <div class='col-sm-6'>    
                    <div class="form-group form-float">
                        <div class="form-line">
                            <label class="form-label">Institution</label>
                            <%= tf.input_field :institution_id, collection: Institution.all, class: "form-control show-tick" %>
                        </div>
                        <%= tf.full_error :institution_id %>
                    </div>
                </div>
                <div class='col-sm-4'>  
                    <div class="form-group form-float">
                        <div class="form-line">
                            <label class="form-label">Amount</label>
                            <%= tf.input_field :amount, class: "form-control show-tick" %>
                        </div>
                        <%= tf.full_error :amount %>
                    </div>
                </div>
                <div class='col-sm-2'>  
                    <%= tf.link_to_remove "remove" %>
                </div>
            </div>
            <%= javascript_include_tag 'AdminBSBMaterialDesign/form_index' %>
        <% end %>
    <p><%= f.link_to_add "Add Funder", :training_funds %></p>
    </div>
    </div>        

app/views/trainings/edit.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "Edit Training" } %>

app/views/trainings/index.html.erb
    <div class="panel-heading">
      Trainings
    </div>
    <div class="panel-body">
    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
      <thead>
        <tr>
          <th>Training title</th>
          <th>Category</th>
          <th>Type</th>
          <th>Organized By</th>
          <th>Start time</th>
          <th>End time</th>
          <th>Location</th>
          <th>Status</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @trainings.each do |training| %>
          <tr>
            <td><%= training.training_title %></td>
            <td><%= training.category %></td>
            <td><%= training.training_type %></td>
            <td><%= training.institution %></td>
            <td><%= training.start_time %></td>
            <td><%= training.end_time %></td>
            <td><%= training.location %></td>
            <td>
              <label class="label <%= training.training_status == Training::NOT_STARTED ? 'label-warning' :
                                          (training.training_status == Training::CANCELED ? 'label-danger' :
                                               (training.training_status == Training::COMPLETED ? 'label-success' : 'label-default')) %>">
                <%= training.training_status %>
              </label>
            </td>
            </td>
            <td>
              <%= link_to training_path(training) do %>
                <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-list"></i> Details</button>
              <% end %>
              <%= link_to edit_training_path(training) do %>
                <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Edit</button>
              <% end %>
                </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <hr/>
     <% if can? :manage, Training %>
      <%= link_to new_training_path do %>
        <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-plus"></i> Add Training</button>
      <% end %>
      <% end %>
</div>

app/views/trainings/new.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "New Training" } %>

app/views/trainings/show.html.erb
<div class="panel-heading">
    Training Session Details
</div>
<div class="panel-body">
  <%= hidden_field_tag 'training', @training.id %>
    <!-- Nav tabs -->
  <ul class="nav nav-tabs tab-nav-right" role="tablist">
    <li role="presentation" class="active"><a href="#training_info" data-toggle="tab"><i class="fa fa-book m-r-5"></i> Training Session</a> </li>
    <li role="presentation"><a href="#funding" data-toggle="tab"><i class="fa fa-dollar m-r-5"></i> Funding</a></li>
    <li role="presentation"><a href="#distribution" data-toggle="tab"><i class="fa fa-check m-r-5"></i> Trainee Assignment </a></li>
    <li role="presentation"><a href="#trainers" data-toggle="tab"> <i class="fa fa-user-circle m-r-5"></i> Trainers</a></li>
    <li role="presentation"><a href="#trainees" data-toggle="tab"><i class="fa fa-group m-r-5"></i> Trainees</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="training_info">
      <ul>
        <li><label class="details-label">Training title:</label> <%= @training.training_title %></td></li>
        <li><label>Category:</label> <%= @training.training_type %></li>
        <li><label>Type:</label> <%= @training.category %></li>
        <li><label>Organized By:</label> <%= @training.institution %></li>
        <li><label>Start date:</label> <%= @training.start_time %></li>
        <li><label>End date:</label> <%= @training.end_time %></li>
        <li><label>Location</label> <%= @training.location %></li>
        <li><label>Description</label> <%= @training.description %></li>
        <li><label>Status</label>
          <label class="label <%= @training.training_status == Training::NOT_STARTED ? 'label-warning' :
                                      (@training.training_status == Training::CANCELED ? 'label-danger' :
                                           (@training.training_status == Training::COMPLETED ? 'label-success' : 'label-default')) %>">
            <%= @training.training_status %>
          </label> &nbsp;&nbsp;<% if @training.status == Training::CANCELED %>
            <%= link_to undo_cancel_training_path(@training), data: { confirm: 'Are you sure you want to re-enable this training session?' } do %>
              <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-check"></i> Undo Cancel</button>
            <% end %>
          <% end %>
        </li>
      </ul>
      <hr/>
      <% unless @training.status == Training::CANCELED %>
      <%= link_to edit_training_path(@training) do %>
        <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Edit</button>
      <% end %>

        <%= link_to cancel_training_path(@training), method: :delete, data: { confirm: 'Are you sure you want to cancel this training session?' } do %>
          <button type="button" class="btn btn-outline btn-danger"><i class="fa fa-remove"></i> Cancel Training</button>
        <% end %>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane fade in" id="funding">
      <% unless @training.training_funds.blank? %>
        <table class="table table-responsive table-condensed">
          <thead>
            <tr>
              <th>Institution</th>
              <th>Amount</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @training.training_funds.each do |tf| %>
                <tr>
                  <td><%= link_to tf.institution, institution_path(tf.institution) %> </td>
                  <td><%= tf.amount %></td>
                  <td>
                    <%= link_to edit_training_fund_path(tf)  do %>
                      <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Edit</button>
                    <% end %>
                  </td>
                </tr>
            <% end %>
          </tbody>
      </table>
      <% end %>
      <hr/>
      <%= link_to new_training_fund_path(training: @training.id) do %>
        <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-plus"></i> Add Funding</button>
      <% end %>

    </div>

    <div role="tabpanel" class="tab-pane fade in" id="distribution">
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-4">
            <div id="trainee_distribution_tree">
            </div>
          </div>

          <div class="col-sm-8">
            <a class="list-group-item">
              <div class="row clearfix">
                <div class="col-sm-8"><label>Maximum Possible Number of Trainees</label></div>
                <div class="col-sm-4"><button class="btn btn-primary btn-block" type="button"><%= @training.max_possible_trainees(current_user.parent_org_unit) %></button></div>
              </div>
            </a><br/>
            <div id="trainee_distributions">
              <table class="table table-striped js-exportable">
                <thead>
                <tr>
                  <th>Organization Unit</th>
                  <th>Number of Trainees</th>
                </tr>
                </thead>

                <tbody>
                <% @trainee_distributions.each do |distribution| %>
                    <tr>
                      <td><%= distribution.organization_unit %></td>
                      <td><%= distribution.number_of_trainees %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>

    <div role="tabpanel" class="tab-pane fade in" id="trainers">
      <table class="table table-bordered table-striped table-hover dataTable js-exportable">
        <thead>
        <tr>
          <th>Trainer Name</th>
          <th>Phone</th>
          <th>Email</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @training.trainers.each do |trainer| %>
            <tr>
              <td><%= trainer.person %></td>
              <td><%= trainer.person.phone_number %></td>
              <td><%= trainer.person.email %></td>
              <td>
                <%= link_to edit_trainer_path(trainer) do %>
                  <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Edit</button>
                <% end %>
                <%= link_to trainer, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <button type="button" class="btn btn-outline btn-danger"><i class="fa fa-edit"></i> Remove</button>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <hr/>
      <%= link_to new_trainer_path(training: @training.id) do %>
        <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Add Trainer</button>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane fade in" id="trainees">
      <table class="table table-striped table-hover dataTable js-exportable">
        <thead>
        <tr>
          <th>Name</th>
          <th>Org Unit</th>
          <th>Facility</th>
          <th>Pre Training Score</th>
          <th>Post Training Score</th>
          <th>Status</th>
          <th>Trainer Feedback</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @training.trainees.each do |trainee| %>
            <tr>
              <td><%= trainee.person %></td>
              <td><%= trainee.person.organization_unit %></td>
              <td><%= trainee.person.facility %></td>
              <td><a><%= best_in_place trainee, :pre_training_score, as: :input, place_holder: "Click here to add value" %></a></td>
              <td><a><%= best_in_place trainee, :post_training_score, :as => :input, place_holder: "Click here to add value" %></a></td>
              <td><a><%= best_in_place trainee, :status, :as => :input, as: :select, collection:
                  [[Trainee::PENDING, Trainee::PENDING], [Trainee::COMPLETED, Trainee::COMPLETED], [Trainee::NOTCOMPLETED, Trainee::NOTCOMPLETED]], :display_as => :status %></a></td>
              <td><a><%= best_in_place trainee, :trainer_feedback, as: :textarea, :as => :textarea, place_holder: "Click here to add value" %></a></td>
              <td>
                <%= link_to trainee, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <button type="button" class="btn btn-outline btn-danger"><i class="fa fa-remove"></i> Remove </button>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <hr/>
      <%= link_to new_trainee_path(training: @training.id) do %>
        <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-plus"></i> Add Trainers </button>
      <% end %>
    </div>

  </div>
</div>