config/routes.rb
Rails.application.routes.draw do
  resources :pages
  mount Thredded::Engine => '/forum'
  resources :support_requests
  resources :board_members_terms
  resources :association_details
  resources :event_applicants
  resources :events do
    member do
      get 'apply'
    end
  end
  resources :payments do
    collection do
      get 'member_fees'
    end
    member do
      get 'confirm'
    end
  end
  resources :mp_amount_settings
  resources :mp_years
  resources :membership_types
  resources :budget_years
  resources :training_materials
  resources :training_methods
  resources :training_funds do
    collection do
      get 'funding_by_area'
    end
  end
  resources :trainee_distributions
  resources :educations
  resources :work_experiences
  resources :trainer_profiles
  resources :languages
  resources :professions
  resources :profession_categories
  get 'reports/trainings'
  post 'reports/trainings'
  get 'reports/health_workers'
  post 'reports/health_workers'
  get 'reports/trainees'
  post 'reports/trainees'
  get 'reports/members'
  post 'reports/members'

  resources :trainees do
    collection do
      get 'load_trainees'
      get 'institution_trainees_by_area'
      get 'institution_trainees_by_region'
      get 'institution_trainees_by_year'

      get 'org_unit_trainees_by_area'
      get 'org_unit_trainees_by_year'
      get 'org_unit_trainees_by_category'
    end
  end
  resources :trainers
  resources :people do
    member do
      get 'membership_idcard'
      get 'confirm'
    end
    collection do
      get 'load_people'
      get 'load_professions'
      get 'members_by_type'
      get 'members_by_membership_type_and_payment_status'
      get 'members_paid'
      get 'load_members_paid'
      get 'members_not_paid'
      get 'load_members_not_paid'
    end
  end
  resources :facilities do
    collection do
      get 'load_facilities'
    end
  end
  resources :facility_types
  resources :trainings do
    collection do
      get 'load_distribution'
    end
    member do
      delete 'cancel'
      get 'undo_cancel'
    end
  end

  resources :training_titles do
    collection do
      get 'training_titles_by_area'
      get 'load_training_titles'
    end
  end

  resources :program_areas
  resources :institutions
  resources :institution_types
  resources :organization_units do
    collection do
      get 'load_tree'
      get 'load_sub_units'
      get 'org_unit_facilities'
    end
  end
  resources :organization_types
  resources :roles
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  scope "/admin" do
    resources :users do
      member do
        get 'confirm'
      end
      collection do
        get 'load_users'
        get 'institution_users'
        get 'new_institution_user'
        get 'edit_institution_user'
      end
    end
  end
  get 'home/index'
  get 'home/landing_page'
  get 'payment_dashboard', to: 'home#payment_dashboard'
  get 'training_dashboard', to: 'home#training_dashboard'
  get 'member_dashboard', to: 'home#member_dashboard'

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  root to: "home#landing_page"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training_title.rb
class TrainingTitle < ApplicationRecord
  belongs_to :program_area
  belongs_to :training_method
  has_many :trainer_training_titles
  has_many :trainer_profiles, through: :trainer_training_titles
  has_many :people, through: :trainer_profiles
  has_many :trainings
  has_many :trainees, through: :trainings
  has_many :training_materials


  has_attached_file :topic_image, styles: { medium: "200*200" }, default_url: "missing/missing-topic.jpg"
  validates_attachment_content_type :topic_image, content_type: /\Aimage\/.*\z/


  validates :title, :program_area_id, :duration, :duration_in,
            :maximum_number_of_participants, :training_method, presence: true

  scope :list_by_program_area, -> (area) { where('program_area_id = ?', area) }
  scope :list_by_title, -> (title) { title.blank? ? [] : where("lower(title) LIKE ?", "#{title.downcase}%") }

  def self.search(program_area, training_title)
    training_titles = []
    if !program_area.blank? and !training_title.blank?
      training_titles = (list_by_program_area(program_area).list_by_title(training_title)).uniq
    elsif !program_area.blank?
      training_titles = list_by_program_area(program_area)
    elsif !training_title.blank?
      training_titles = list_by_title(training_title)
    end
    return training_titles
  end

  def trainers
    (trainer_profiles.collect{ |tp| tp.person } + trainees.joins(:training).where('trainings.category = ? and trainees.status = ?', 'TOT',Trainee::COMPLETED).collect{ |tt| tt.person }).uniq
  end

  def to_s
    title
  end

end

app/controllers/training_titles_controller.rb
class TrainingTitlesController < ApplicationController
  before_action :set_training_title, only: [:show, :edit, :update, :destroy]

  def training_titles_by_area
    render json: TrainingTitle.joins(:program_area).group('name').count
  end

  def load_training_titles
    @filtered_training_titles = TrainingTitle.search(params[:program_area],params[:training_title])
    render partial: 'training_titles'
  end

  # GET /training_titles
  # GET /training_titles.json
  def index
    @training_titles = TrainingTitle.all
    @filtered_training_titles = TrainingTitle.all
  end

  # GET /training_titles/1
  # GET /training_titles/1.json
  def show
  end

  # GET /training_titles/new
  def new
    @training_title = TrainingTitle.new
  end

  # GET /training_titles/1/edit
  def edit
  end

  # POST /training_titles
  # POST /training_titles.json
  def create
    @training_title = TrainingTitle.new(training_title_params)

    respond_to do |format|
      if @training_title.save
        format.html { redirect_to training_titles_path, notice: 'Training title was successfully created.' }
        format.json { render :show, status: :created, location: @training_title }
      else
        format.html { render :new }
        format.json { render json: @training_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /training_titles/1
  # PATCH/PUT /training_titles/1.json
  def update
    respond_to do |format|
      if @training_title.update(training_title_params)
        format.html { redirect_to training_titles_path, notice: 'Training title was successfully updated.' }
        format.json { render :show, status: :ok, location: @training_title }
      else
        format.html { render :edit }
        format.json { render json: @training_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_titles/1
  # DELETE /training_titles/1.json
  def destroy
    @training_title.destroy
    respond_to do |format|
      format.html { redirect_to training_titles_url, notice: 'Training title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training_title
      @training_title = TrainingTitle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_title_params
      params.require(:training_title).permit(:title, :program_area_id, :duration, :duration_in,
                                             :maximum_number_of_participants, :training_method_id, :description, :topic_image)
    end
end

app/helpers/training_titles_helper.rb
module TrainingTitlesHelper
end

app/views/training_titles/_form.html.erb
<%= simple_form_for(@training_title) do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, class: "form-control show-tick" %>
  <%= f.input :program_area_id, collection: ProgramArea.all, class: "form-control show-tick" %>
  <%= f.input :duration, class: "form-control show-tick" %>
  <%= f.input :duration_in, as: :radio_buttons,  item_wrapper_tag: :span, wrapper: 'horizontal_collection', collection: ['Hours','Days','Weeks'] %>
  <%= f.input :maximum_number_of_participants, class: "form-control show-tick" %>
  <%= f.association :training_method %>
  <%= f.input :description, class: "form-control show-tick" %>
  <%= f.input :topic_image, as: :file %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/training_titles/_training_titles.html.erb
<% @filtered_training_titles.each do |training_title| %>
  <div class="col-sm-3">
    <div class="panel panel-default">
      <div class="panel-heading"><%= training_title %></div>
      <div class="panel-body">
        <div>
          <%= image_tag(training_title.topic_image.url(:medium), width: '100%', height: 200) %>
          <h4><%= training_title.description %></h4>
          <p>Program Area: <b><%= training_title.program_area %></b></p>
          <p>Duration: <b><%= training_title.duration %> <%= training_title.duration_in %></b></p>
          <p>Training Method: <b><%= training_title.training_method %></b></p>
          <hr/>
          <p class="pull-right">
            <%= link_to edit_training_title_path(training_title) do %>
              <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Edit </button>
            <% end %>
            <%= link_to training_title do %>
              <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-list"></i> Details </button>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/training_titles/edit.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "Edit Training Topic" } %>

app/views/training_titles/index.html.erb
<% content_for :header do %>
  <div class="row clearfix">
    <%= simple_form_for :search, url: training_titles_path do |f| %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.input :program_area, collection: ProgramArea.all %>
        </div>
        <div class="col-sm-6">
          <%= f.input :training_title %>
        </div>
      </div>
    <% end %>
    <div id="filtered_training_titles">
      <%= render 'training_titles' %>
    </div>
  </div>
<% end %>
<br>
<%= link_to new_training_title_path do %>
  <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-plus"></i> Add Training Topic </button>
<% end %>

app/views/training_titles/new.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "New Training Topic" } %>

app/views/training_titles/show.html.erb
<div class="panel-heading">
  Training Topic Details
</div>

<div class="panel-body">
  <div class="col-sm-4">
    <p>
      <strong>Title:</strong>
      <%= @training_title.title %>
    </p>

    <p>
      <strong>Program area:</strong>
      <%= @training_title.program_area %>
    </p>

    <p>
      <strong>Training Method:</strong>
      <%= @training_title.training_method %>
    </p>

    <p>
      <strong>Durarion:</strong>
      <%= @training_title.duration %> <%= @training_title.duration_in %>
    </p>

    <p>
      <strong>Maximum Number of Participants:</strong>
      <%= @training_title.maximum_number_of_participants %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @training_title.description %>
    </p>
    <hr/>
    <%= link_to edit_training_title_path(@training_title) do %>
      <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Edit Training Topic</button>
    <% end %>
  </div>

  <legend class="col-sm-8" style="border-left: 1px solid silver">
    <legend>
      Training Sessions
    </legend>
    <div class="panel-body">
      <table class="table js-exportable">
        <thead>
        <tr>
          <th>Category</th>
          <th>Type</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Location</th>
          <th>Status</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          <% for training in @training_title.trainings %>
          <tr>
            <td><%= training.training_type %></td>
            <td><%= training.category %></td>
            <td><%= training.start_time %></td>
            <td><%= training.end_time %></td>
            <td><%= training.location %></td>
            <td>
              <label class="label <%= training.training_status == Training::NOT_STARTED ? 'label-warning' :
                                                                        (training.training_status == Training::CANCELED ? 'label-danger' :
                                                                             (training.training_status == Training::COMPLETED ? 'label-success' : 'label-default')) %>">
              <%= training.training_status %>
              </label>
            </td>
            <td>
              <%= link_to training do %>
                <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-list"></i> Details</button>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <hr/>
      <%= link_to new_training_path(training_title: @training_title.id) do %>
        <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-plus"></i> Create New Training Session</button>
      <% end %>
    </div>
  </div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
  Training Materials
</div>

<div class="panel-body">
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Attachment</th>
      <th></th>
    </tr>
    </thead>
    <% for material in @training_title.training_materials do %>
    <tr>
      <td><%= material.name %></td>
      <td>
        <% unless material.attachment.blank? %>
          <%= link_to material.attachment.url do %>
            <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-download"></i> Download</button>
          <% end %>
        <% end %>
      </td>
      <td>
        <%= link_to edit_training_material_url(material) do %>
          <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Edit</button>
        <% end %>
        <%= link_to material, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <button type="button" class="btn btn-outline btn-danger"><i class="fa fa-remove"></i> Remove</button>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>

  <button type="button" class="btn btn-outline btn-primary" data-toggle="modal" data-target="#defaultModal"><i class="fa fa-plus"></i> Add Training Material</button>

  <div class="modal fade" id="defaultModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="defaultModalLabel">New Training Material</h4>
        </div>
        <div class="modal-body">
          <%= simple_form_for(TrainingMaterial.new) do |f| %>
            <%= f.error_notification %>

            <div class="form-inputs">
              <%= f.association :training_title, collection: [@training_title], prompt: false %>
              <%= f.input :name %>
              <%= f.input :attachment, as: :file %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>