config/routes.rb
Rails.application.routes.draw do
  resources :pages
  mount Thredded::Engine => '/forum'
  resources :support_requests
  resources :board_members_terms
  resources :association_details
  resources :event_applicants
  resources :events do
    member do
      get 'apply'
    end
  end
  resources :payments do
    collection do
      get 'member_fees'
    end
    member do
      get 'confirm'
    end
  end
  resources :mp_amount_settings
  resources :mp_years
  resources :membership_types
  resources :budget_years
  resources :training_materials
  resources :training_methods
  resources :training_funds do
    collection do
      get 'funding_by_area'
    end
  end
  resources :trainee_distributions
  resources :educations
  resources :work_experiences
  resources :trainer_profiles
  resources :languages
  resources :professions
  resources :profession_categories
  get 'reports/trainings'
  post 'reports/trainings'
  get 'reports/health_workers'
  post 'reports/health_workers'
  get 'reports/trainees'
  post 'reports/trainees'
  get 'reports/members'
  post 'reports/members'

  resources :trainees do
    collection do
      get 'load_trainees'
      get 'institution_trainees_by_area'
      get 'institution_trainees_by_region'
      get 'institution_trainees_by_year'

      get 'org_unit_trainees_by_area'
      get 'org_unit_trainees_by_year'
      get 'org_unit_trainees_by_category'
    end
  end
  resources :trainers
  resources :people do
    member do
      get 'membership_idcard'
      get 'confirm'
    end
    collection do
      get 'load_people'
      get 'load_professions'
      get 'members_by_type'
      get 'members_by_membership_type_and_payment_status'
      get 'members_paid'
      get 'load_members_paid'
      get 'members_not_paid'
      get 'load_members_not_paid'
    end
  end
  resources :facilities do
    collection do
      get 'load_facilities'
    end
  end
  resources :facility_types
  resources :trainings do
    collection do
      get 'load_distribution'
    end
    member do
      delete 'cancel'
      get 'undo_cancel'
    end
  end

  resources :training_titles do
    collection do
      get 'training_titles_by_area'
      get 'load_training_titles'
    end
  end

  resources :program_areas
  resources :institutions
  resources :institution_types
  resources :organization_units do
    collection do
      get 'load_tree'
      get 'load_sub_units'
      get 'org_unit_facilities'
    end
  end
  resources :organization_types
  resources :roles
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  scope "/admin" do
    resources :users do
      member do
        get 'confirm'
      end
      collection do
        get 'load_users'
        get 'institution_users'
        get 'new_institution_user'
        get 'edit_institution_user'
      end
    end
  end
  get 'home/index'
  get 'home/landing_page'
  get 'payment_dashboard', to: 'home#payment_dashboard'
  get 'training_dashboard', to: 'home#training_dashboard'
  get 'member_dashboard', to: 'home#member_dashboard'

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  root to: "home#landing_page"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trainee_distribution.rb
class TraineeDistribution < ApplicationRecord
  belongs_to :training
  belongs_to :organization_unit

  validates :training_id, :organization_unit_id, :number_of_trainees, presence: true
end

app/controllers/trainee_distributions_controller.rb
class TraineeDistributionsController < ApplicationController
  before_action :set_trainee_distribution, only: [:show, :edit, :update, :destroy]
  before_action :load_org_units

  def load_org_units
    if current_user.organization_unit
      @org_units = current_user.parent_org_unit.sub_organization_units
    else
      @org_units = OrganizationUnit.all
    end
  end

  # GET /trainee_distributions
  # GET /trainee_distributions.json
  def index
    @training = Training.find(params[:training])
    @trainee_distributions = @training.trainee_distributions
  end

  # GET /trainee_distributions/1
  # GET /trainee_distributions/1.json
  def show
  end

  # GET /trainee_distributions/new
  def new
    @trainee_distribution = TraineeDistribution.new
    @trainee_distribution.training_id = params[:training]
  end

  # GET /trainee_distributions/1/edit
  def edit
  end

  # POST /trainee_distributions
  # POST /trainee_distributions.json
  def create
    @training = Training.find(params[:training])
    max_number_of_trainees = @training.max_possible_trainees(current_user.parent_org_unit)
    trainees = params["distributions"].select{|t| !t['number_of_trainees'].blank? }
    total_distribution = trainees.collect{|t| t['number_of_trainees'].to_i}.sum
    if total_distribution > max_number_of_trainees
      flash[:alert] = "The sum should not exceed the possible number of trainees which is #{max_number_of_trainees}"
      redirect_to @training
    else
      params["distributions"].each do |trainee_distribution|
        unless trainee_distribution["number_of_trainees"].blank?
          org_unit = OrganizationUnit.find(trainee_distribution['organization_unit_id'])
          unless org_unit.trainee_distribution(@training.id).blank?
            org_unit.trainee_distribution(@training.id).update(trainee_distribution_params(trainee_distribution))
          else
            TraineeDistribution.create(trainee_distribution_params(trainee_distribution))
          end
        end
      end
      unless trainees.blank?
        flash[:notice] = "Successfully assigned"
      else
        flash[:alert] = "No assignment added"
      end
      redirect_to @training
    end
  end

  # PATCH/PUT /trainee_distributions/1
  # PATCH/PUT /trainee_distributions/1.json
  def update
  end

  # DELETE /trainee_distributions/1
  # DELETE /trainee_distributions/1.json
  def destroy
    @trainee_distribution.destroy
    respond_to do |format|
      format.html { redirect_to trainee_distributions_url, notice: 'Trainee distribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainee_distribution
      @trainee_distribution = TraineeDistribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainee_distribution_params(my_params)
      my_params.permit(:training_id, :organization_unit_id, :number_of_trainees)
    end
end

app/helpers/trainee_distributions_helper.rb
module TraineeDistributionsHelper
end

app/views/trainee_distributions/_form.html.erb
<%= simple_form_for(@trainee_distribution) do |f| %>
    <%= f.error_notification %>
    <%= f.input :training_id, collection: [@trainee_distribution.training], prompt: false, class: "form-control show-tick" %>
    <%= f.input :organization_unit_id, collection: @org_units, class: "form-control show-tick" %>
    <%= f.input :number_of_trainees, class: "form-control show-tick" %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/trainee_distributions/edit.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "Edit Trainee Distribution" } %>

app/views/trainee_distributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainee Distributions</h1>

<table>
  <thead>
    <tr>
      <th>Training</th>
      <th>Organization unit</th>
      <th>Number of trainees</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainee_distributions.each do |trainee_distribution| %>
      <tr>
        <td><%= trainee_distribution.training %></td>
        <td><%= trainee_distribution.organization_unit %></td>
        <td><%= trainee_distribution.number_of_trainees %></td>
        <td><%= link_to 'Show', trainee_distribution %></td>
        <td><%= link_to 'Edit', edit_trainee_distribution_path(trainee_distribution) %></td>
        <td><%= link_to 'Destroy', trainee_distribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainee Distribution', new_trainee_distribution_path %>

app/views/trainee_distributions/new.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "New Trainee Distribution" } %>

app/views/trainee_distributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Training:</strong>
  <%= @trainee_distribution.training %>
</p>

<p>
  <strong>Organization unit:</strong>
  <%= @trainee_distribution.organization_unit %>
</p>

<p>
  <strong>Number of trainees:</strong>
  <%= @trainee_distribution.number_of_trainees %>
</p>

<%= link_to 'Edit', edit_trainee_distribution_path(@trainee_distribution) %> |
<%= link_to 'Back', trainee_distributions_path %>