config/routes.rb
Rails.application.routes.draw do
  resources :pages
  mount Thredded::Engine => '/forum'
  resources :support_requests
  resources :board_members_terms
  resources :association_details
  resources :event_applicants
  resources :events do
    member do
      get 'apply'
    end
  end
  resources :payments do
    collection do
      get 'member_fees'
    end
    member do
      get 'confirm'
    end
  end
  resources :mp_amount_settings
  resources :mp_years
  resources :membership_types
  resources :budget_years
  resources :training_materials
  resources :training_methods
  resources :training_funds do
    collection do
      get 'funding_by_area'
    end
  end
  resources :trainee_distributions
  resources :educations
  resources :work_experiences
  resources :trainer_profiles
  resources :languages
  resources :professions
  resources :profession_categories
  get 'reports/trainings'
  post 'reports/trainings'
  get 'reports/health_workers'
  post 'reports/health_workers'
  get 'reports/trainees'
  post 'reports/trainees'
  get 'reports/members'
  post 'reports/members'

  resources :trainees do
    collection do
      get 'load_trainees'
      get 'institution_trainees_by_area'
      get 'institution_trainees_by_region'
      get 'institution_trainees_by_year'

      get 'org_unit_trainees_by_area'
      get 'org_unit_trainees_by_year'
      get 'org_unit_trainees_by_category'
    end
  end
  resources :trainers
  resources :people do
    member do
      get 'membership_idcard'
      get 'confirm'
    end
    collection do
      get 'load_people'
      get 'load_professions'
      get 'members_by_type'
      get 'members_by_membership_type_and_payment_status'
      get 'members_paid'
      get 'load_members_paid'
      get 'members_not_paid'
      get 'load_members_not_paid'
    end
  end
  resources :facilities do
    collection do
      get 'load_facilities'
    end
  end
  resources :facility_types
  resources :trainings do
    collection do
      get 'load_distribution'
    end
    member do
      delete 'cancel'
      get 'undo_cancel'
    end
  end

  resources :training_titles do
    collection do
      get 'training_titles_by_area'
      get 'load_training_titles'
    end
  end

  resources :program_areas
  resources :institutions
  resources :institution_types
  resources :organization_units do
    collection do
      get 'load_tree'
      get 'load_sub_units'
      get 'org_unit_facilities'
    end
  end
  resources :organization_types
  resources :roles
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  scope "/admin" do
    resources :users do
      member do
        get 'confirm'
      end
      collection do
        get 'load_users'
        get 'institution_users'
        get 'new_institution_user'
        get 'edit_institution_user'
      end
    end
  end
  get 'home/index'
  get 'home/landing_page'
  get 'payment_dashboard', to: 'home#payment_dashboard'
  get 'training_dashboard', to: 'home#training_dashboard'
  get 'member_dashboard', to: 'home#member_dashboard'

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  root to: "home#landing_page"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  respond_to :js
  def trainings
    @trainings = []
    if request.post?
      if params[:training_type] or params[:program_area] or params[:training_title]
        @trainings = Training.search_by_tpt(params[:training_type],params[:program_area],params[:training_title])
        respond_to do |format|
          format.js
        end
      end
    end
  end

  def health_workers
    @health_workers = []
  end

  def trainees
    @trainees = []
    if request.post?
      @trainees = Trainee.search(params[:search][:organization_unit], params[:search][:program_area], params[:search][:training_title],
                                 params[:search][:category], params[:search][:training_type], params[:search][:trainee_status])
      respond_to do |format|
        format.js
        format.html
      end
    end
  end

    def members
      @members = []
      if request.post?
        status = params[:search][:payment_status] == 'true' ? true : false
        @members = Person.search(current_user,params[:search][:organization_unit], params[:search][:membership_type],
                                 params[:search][:budget_year],status)
        respond_to do |format|
          format.js
          format.html
        end
      end
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_health_workers.html.erb
<div class="body table-responsive">
  <table class="table table-bordered table-striped table-hover dataTable js-exportable">
    <thead>
    <tr>
      <th>Name</th>
      <th>Organization Unit</th>
      <th>Facility</th>
      <th>Phone</th>
      <th>Email</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @health_workers.each do |health_worker| %>
        <tr>
          <td><%= health_worker.full_name %></td>
          <td><%= health_worker.organization_unit %></td>
          <td><%= health_worker.facility %></td>
          <td><%= health_worker.phone_number %></td>
          <td><%= health_worker.email %></td>
          <td><%= link_to 'Details', person_path(health_worker) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/reports/_members.html.erb
<div class="body table-responsive">
  <table class="table table-bordered table-striped table-hover dataTable js-exportable">
    <thead>
    <tr>
      <th>Name</th>
      <th>Membership Type</th>
      <th>Org Unit / Facility</th>
      <th>Phone Number</th>
      <th>Email</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @members.each do |person| %>
        <tr>
          <td><%= person.full_name %></td>
          <td><%= person.membership_type %></td>
          <td><%= person.organization_unit || person.facility %></td>
          <td><%= person.phone_number %></td>
          <td><%= person.email %></td>
          <td>
            <%= link_to person_path(person) do %>
                <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-list"></i> Details</button>
            <% end %>
            <%= link_to edit_person_path(person) do %>
                <button type="button" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i> Edit</button>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br>

</div>

app/views/reports/_trainees.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Trainees Search Result
  </div>
  <div class="panel-body">
    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
      <thead>
      <tr>
        <th>Name</th>
        <th>Org Unit</th>
        <th>Facility</th>
        <th>Training Topic</th>
        <th>Category</th>
        <th>Training Type</th>
        <th>Pre Training Score</th>
        <th>Post Training Score</th>
        <th>Trainee Status</th>
        <th>Trainer Feedback</th>
      </tr>
      </thead>

      <tbody>
      <% @trainees.each do |trainee| %>
        <tr>
          <td><%= trainee.person %></td>
          <td><%= trainee.person.organization_unit %></td>
          <td><%= trainee.person.facility %></td>
          <td><%= trainee.training.training_title %></td>
          <td><%= trainee.training.training_type %></td>
          <td><%= trainee.training.category %></td>
          <td><%= trainee.pre_training_score %></td>
          <td><%= trainee.post_training_score%></td>
          <td><%= trainee.status %></td>
          <td><%= trainee.trainer_feedback %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/reports/_trainings.html.erb
<div class="panel-body">
  <table class="table table-bordered table-striped table-hover dataTable js-exportable">
    <thead>
    <tr>
      <th>Training title</th>
      <th>Training type</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Location</th>
    </tr>
    </thead>

    <tbody>
    <% @trainings.each do |training| %>
        <tr>
          <td><%= training.training_title %></td>
          <td><%= training.training_type %></td>
          <td><%= training.start_time %></td>
          <td><%= training.end_time %></td>
          <td><%= training.location %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/reports/health_workers.html.erb
<div class="panel-heading">
  Health Workers Report
</div>

<div class="panel-body">
  <%= form_tag reports_health_workers_path, :remote => true do %>

      <div class="row">
        <div class="col-sm-4">Facility </div>
        <div class="col-sm-8">
          <%= select_tag "facility", options_from_collection_for_select(Facility.all, "id", "name"),{include_blank: true, class: 'form-control'} %>
        </div>
      </div><br/>

      <div class="row">
        <div class="col-sm-4">Training Type</div>
        <div class="col-sm-8">
          <%= select(nil, "training_type", ["Pre-Service", "In-Service"].collect{|x| x},{include_blank: true}, class: 'form-control') %>
        </div>
      </div><br/>

      <div class="row">
        <div class="col-sm-4">Training Title </div>
        <div class="col-sm-8">
          <%= select_tag "training_title", options_from_collection_for_select(TrainingTitle.all, "id", "title"),{include_blank: true, class: 'form-control'} %>
        </div>
      </div><br/>
      <div class="row">
        <div class="col-sm-offset-4 col-sm-8">
          <%= submit_tag 'Search' %>
        </div>
      </div>

  <% end %>


  <div id="health_workers_report">
    <%= render partial: 'health_workers' %>
  </div>

</div>

app/views/reports/health_workers.js.erb
$("#health_workers_report").html("<%= escape_javascript( render :partial => "health_workers"  ) %>");
$("#health_workers_report").fadeIn(500);
$('.js-exportable').DataTable({
    dom: 'lrBfrtip',
    responsive: true,
    buttons: [
        'copy', 'csv', 'excel', 'pdf', 'print'
    ]
});

app/views/reports/members.html.erb
<div class="panel-heading">
  Members Report
</div>

<div class="panel-body">
  <%= simple_form_for :search, url:  reports_members_path, remote: true, html: { novalidate: true } do |f| %>

      <div class="row">
        <div class="col-sm-6">
          <fieldset class="sub_form">
            <legend>Members</legend>
          <div id="report_members_organization_unit_tree"></div>
          <%=  f.input :organization_unit, as: :hidden, required: false %>
          <%=  f.input :membership_type, collection: MembershipType.all, required: false %>
          </fieldset>
        </div>
        <div class="col-sm-6">
          <fieldset class="sub_form">
            <legend>Payment Status</legend>
          <%=  f.input :budget_year, collection: BudgetYear.all, required: false %>
          <%=  f.input :payment_status, collection: [['Paid', true], ['Not Paid', false]], required: false %>
          </fieldset>
        </div>
      </div>
      <div class="form-actions">
        <%= f.button :button, 'Reset Form', type: :reset, class: 'btn btn-default' %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= f.button :submit, 'Search', class: 'btn btn-primary' %>
      </div>
  <% end %>


  <div id="members_report">
    <%= render 'members' %>
  </div>
</div>

app/views/reports/members.js.erb
$("#members_report").html("<%= escape_javascript( render :partial => "members"  ) %>");
$("#members_report").fadeIn(500);
$('.js-exportable').DataTable({
    dom: 'lrBfrtip',
    responsive: true,
    buttons: [
        'copy', 'csv', 'excel', 'pdf', 'print'
    ]
});

app/views/reports/trainees.html.erb
<div class="panel-heading">
  Trainees Report
</div>

<div class="panel-body">
  <%= simple_form_for :search, url:  reports_trainees_path, remote: true, html: { novalidate: true } do |f| %>

    <div class="row">
      <div class="col-sm-4">
        <div id="report_organization_unit_tree"></div>
          <%=  f.input :organization_unit, as: :hidden, required: false %>
      </div>
      <div class="col-sm-4">
        <%=  f.input :program_area, collection: ProgramArea.all, required: false %>
        <%=  f.input :training_title, collection: TrainingTitle.all, required: false %>
        <%=  f.input :category, collection: ['In-Service', 'Pre-Service'], required: false %>
      </div>
      <div class="col-sm-4">
        <%=  f.input :training_type, collection: ['Basic', 'Refreshment', 'TOT'], required: false %>
        <%=  f.input :trainee_status, collection: Trainee::STATUSES, required: false %>
      </div>
      </div>
    </div>
    <div class="form-actions">
      <%= f.button :button, 'Reset Form', type: :reset, class: 'btn btn-default' %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= f.button :submit, 'Search', class: 'btn btn-primary' %>
    </div>
  <% end %>


  <div id="trainees_report">
    <%= render 'trainees' %>
  </div>

</div>

app/views/reports/trainees.js.erb
$("#trainees_report").html("<%= escape_javascript( render :partial => "trainees"  ) %>");
$("#trainees_report").fadeIn(500);
$('.js-exportable').DataTable({
    dom: 'lrBfrtip',
    responsive: true,
    buttons: [
        'copy', 'csv', 'excel', 'pdf', 'print'
    ]
});

app/views/reports/trainings.html.erb
<div class="panel-heading">
    Report
</div>

<div class="panel-body">
  <%= simple_form_for reports_trainings_path, :remote => true do |f| %>
<div class="row">
    <div class="col-sm-6">
      <%= f.input :training_type, as: :radio_buttons, item_wrapper_tag: 'span', collection: ["Pre-Service", "In-Service"] %>
  </div>

    <div class="col-sm-6">
      <%= f.input :program_area, collection: ProgramArea.all %>
      <%= f.input :training_title, collection: TrainingTitle.all %>
  </div>
</div>
    <div class="row">
      <div class="col-sm-offset-4 col-sm-8">
        <%= f.button :submit, 'Search' %>
      </div>
    </div>

  <% end %>
<hr/>

  <div id="training_report">
      <%= render partial: 'trainings' %>
  </div>

</div>

app/views/reports/trainings.js.erb
$("#training_report").html("<%= escape_javascript( render :partial => "trainings"  ) %>");
$("#training_report").fadeIn(500);
    $('.js-exportable').DataTable({
        dom: 'lrBfrtip',
        responsive: true,
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    });